package static

const (
	// TWITTERREQUESTSLIMIT :
	TWITTERREQUESTSLIMIT = 900
	// TWITTERPATCHSIZE :
	TWITTERPATCHSIZE = 99
	// RESULTPATCHSIZE :
	RESULTPATCHSIZE = 10
	// STORAGEDIR :
	STORAGEDIR = "result"
)
